WOGQA:
  site:  qa.writeonglass.com
  ssl:   yes
  environment_id: 5
  shared: [ RetrollectAppQA, Demo ]
RetrollectAppQA:
  site:  retrollect-qa.writeonglass.com
  ssl:   yes
  uri:   api
  shared: [ WOGQA, Demo ]
  environment_id: 30
BoStyQA:
  site:  qa.borderstylo.com
MediaQA:
  site:  media-qa.writeonglass.com
DistopiaTest:
  site:  distopiatest.writeonglass.com
  ssl:   yes
  environment_id: 47
